/*!
 * js/legendary-recipes.js - CONTRATO de fabricacion de las 206 legendarias
 * Proyecto: Boveda del Gato Negro (GW2 Wallet Ligero)
 * Version: 1.0.0
 * Generado: 2026-10-02 03:38:10 UTC
 *
 * Generado por js/_build_legendary_recipes.py desde tools/cl_recipes.json.
 * NO modificar manualmente. El encabezado de ese script explica por que el
 * contrato existe y por que lista los 206 items y no solo los que tienen
 * receta.
 *
 * CONTRATO
 *   craftType  'mystic_forge' | 'crafting' | 'none'
 *   dataStatus 'recipe' | 'no_recipe' | 'placeholder'
 *
 * 'crafting' es de primera clase: las 18 piezas Obsidian (6 por peso) son
 * 'crafting' con disciplina y NO tienen receta de Forja Mistica. Un
 * hasRecipe:boolean laseria igual a las de la forja y perderia eso.
 *
 * Reparto medido sobre los 206 items:
 *   craftType   mystic_forge=124  crafting=18  none=64
 *   dataStatus  recipe=142  no_recipe=63  placeholder=1
 * Fuente: 634 recetas (crafting=352, mystic_forge=278, vendor=4)
 *
 * Verificacion de datos (2026-10-02, tools/hb122-verificar-items.cjs):
 *   1135/1136 ids existen en /v2/items. El unico que no es item_id 0
 *   ('Relic (any)'), de UNA receta de vendor que no es del catalogo.
 *   0 cantidades no enteras positivas, 0 nombres vacios, 0 nombres que
 *   difieren de la API. Muestra manual del 5%: 49 de 930, los 49.
 */

(function (root) {
  'use strict';

  var CRAFT_TYPE = {
    MYSTIC_FORGE: 'mystic_forge',
    CRAFTING: 'crafting',
    NONE: 'none'
  };

  var DATA_STATUS = {
    RECIPE: 'recipe',
    NO_RECIPE: 'no_recipe',
    PLACEHOLDER: 'placeholder'
  };

  // El texto de 'no hay receta' y el del placeholder viven ACA y no en las
  // 63 entradas, por dos razones: son la misma frase 63 veces (y 63 KB de
  // datos que pueden quedar viejos en un solo lugar), y el placeholder tiene
  // que ser una UNICA constante: es el patron contra el que se chequea que
  // GW2 no le cambio el nombre.
  var NO_RECIPE_NOTE = "La fuente (tools/cl_recipes.json) no publica receta para esta pieza. No es lo mismo que 'sin datos': el id se verifico contra /v2/items y existe, y el resto de la fuente se pudo leer. Lo que no hay es la receta.";
  var PLACEHOLDER_NOTE = "Marcador de cuenta, no una legendaria. GW2 lo crea al desbloquear una legendaria y por eso aparece en el catalogo con un nombre propio. Si GW2 le cambia el nombre, el filtro tiene que dejar de matchear y eso tiene que verse; por eso esta declarado aca y no descartado en silencio.";

  var PLACEHOLDER = {
    id: 95093,
    name: "Legendary Equipment Unlocked!",
    note: PLACEHOLDER_NOTE
  };

  // Las claves son el id del catalogo (NUMBER en legendary-data.js). La
  // fuente los tiene como STRING; se comparan igual como clave de objeto
  // porque JS convierte la clave, pero en un Set o un === no. Por eso
  // `get()` normaliza con Number() en vez de confiar en el que llama.
  var BY_ITEM = {
    "30684": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30684, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29166, "count": 1, "name": "Tooth of Frostfang" }, { "itemId": 19625, "count": 1, "name": "Gift of Frostfang" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30685": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30685, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29172, "count": 1, "name": "Leaf of Kudzu" }, { "itemId": 19644, "count": 1, "name": "Gift of Kudzu" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30686": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30686, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29178, "count": 1, "name": "The Lover" }, { "itemId": 19660, "count": 1, "name": "Gift of The Dreamer" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30687": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30687, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29167, "count": 1, "name": "Spark" }, { "itemId": 19645, "count": 1, "name": "Gift of Incinerator" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30688": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30688, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29168, "count": 1, "name": "The Bard" }, { "itemId": 19646, "count": 1, "name": "Gift of The Minstrel" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30689": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30689, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 95081, "count": 1, "name": "Memory of Sunrise" }, { "itemId": 95086, "count": 1, "name": "Memory of Twilight" }, { "itemId": 24277, "count": 5, "name": "Pile of Crystalline Dust" }, { "itemId": 20796, "count": 10, "name": "Philosopher's Stone" }] },
    "30690": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30690, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29170, "count": 1, "name": "The Colossus" }, { "itemId": 19649, "count": 1, "name": "Gift of The Juggernaut" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30691": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30691, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29171, "count": 1, "name": "Carcharias" }, { "itemId": 19657, "count": 1, "name": "Gift of Kamohoali'i Kotaki" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30692": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30692, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29173, "count": 1, "name": "The Energizer" }, { "itemId": 19650, "count": 1, "name": "Gift of The Moot" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30693": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30693, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29174, "count": 1, "name": "Chaos Gun" }, { "itemId": 19651, "count": 1, "name": "Gift of Quip" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30694": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30694, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29175, "count": 1, "name": "The Hunter" }, { "itemId": 19661, "count": 1, "name": "Gift of The Predator" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30695": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30695, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29176, "count": 1, "name": "Storm" }, { "itemId": 19652, "count": 1, "name": "Gift of Meteorlogicus" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30696": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30696, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29177, "count": 1, "name": "The Chosen" }, { "itemId": 19653, "count": 1, "name": "Gift of The Flameseeker Prophecies" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30697": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30697, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29179, "count": 1, "name": "Rage" }, { "itemId": 19659, "count": 1, "name": "Gift of Frenzy" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30698": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30698, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29180, "count": 1, "name": "The Legend" }, { "itemId": 19654, "count": 1, "name": "Gift of The Bifrost" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30699": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30699, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29181, "count": 1, "name": "Zap" }, { "itemId": 19655, "count": 1, "name": "Gift of Bolt" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30700": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30700, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29182, "count": 1, "name": "Rodgort's Flame" }, { "itemId": 19656, "count": 1, "name": "Gift of Rodgort" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30701": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30701, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29183, "count": 1, "name": "Venom" }, { "itemId": 19658, "count": 1, "name": "Gift of Kraitkin" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30702": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30702, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29184, "count": 1, "name": "Howl" }, { "itemId": 19662, "count": 1, "name": "Gift of Howler" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30703": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30703, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29169, "count": 1, "name": "Dawn" }, { "itemId": 19647, "count": 1, "name": "Gift of Sunrise" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }] },
    "30704": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 30704, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 29185, "count": 1, "name": "Dusk" }, { "itemId": 19648, "count": 1, "name": "Gift of Twilight" }, { "itemId": 19674, "count": 1, "name": "Gift of Mastery" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }] },
    "71383": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 71383, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 74068, "count": 1, "name": "The Raven Staff" }, { "itemId": 74300, "count": 1, "name": "Gift of Nevermore" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "72713": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 72713, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 76399, "count": 1, "name": "Prototype" }, { "itemId": 77086, "count": 1, "name": "Gift of HOPE" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "76158": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 76158, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 71426, "count": 1, "name": "The Mechanism" }, { "itemId": 71972, "count": 1, "name": "Gift of Astralaria" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "78556": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 78556, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 78425, "count": 1, "name": "Tigris" }, { "itemId": 78627, "count": 1, "name": "Gift of Chuka and Champawat" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "79562": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 79562, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 79570, "count": 1, "name": "Endeavor" }, { "itemId": 79419, "count": 1, "name": "Gift of Eureka" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "79802": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 79802, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 79836, "count": 1, "name": "Friendship" }, { "itemId": 79839, "count": 1, "name": "Gift of Shooshadoo" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "80488": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80488, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80135, "count": 1, "name": "Man o' War" }, { "itemId": 80650, "count": 1, "name": "Gift of Divinity" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "81206": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 81206, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81022, "count": 1, "name": "Liturgy" }, { "itemId": 81144, "count": 1, "name": "Gift of Balthazar" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "81839": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 81839, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81634, "count": 1, "name": "Might of Arah" }, { "itemId": 81684, "count": 1, "name": "Gift of Arah" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "81957": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 81957, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81812, "count": 1, "name": "Save the Queen" }, { "itemId": 82003, "count": 1, "name": "Gift of the Blade" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "86098": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 86098, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 86097, "count": 1, "name": "Ars Goetia" }, { "itemId": 85744, "count": 1, "name": "Gift of Ipos" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "87687": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 87687, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 87764, "count": 1, "name": "Call of the Void" }, { "itemId": 88060, "count": 1, "name": "Gift of Verdarach" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "88576": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 88576, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 88851, "count": 1, "name": "Tlehco" }, { "itemId": 88500, "count": 1, "name": "Gift of Xiuquatl" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "89854": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 89854, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 89886, "count": 1, "name": "Spero" }, { "itemId": 89445, "count": 1, "name": "Gift of Pharus" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "90551": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 90551, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 90883, "count": 1, "name": "Exitare" }, { "itemId": 90893, "count": 1, "name": "Gift of Exordium" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "103815": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 103815, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 102514, "count": 1, "name": "Gift of Janthir Wilds" }, { "itemId": 102376, "count": 1, "name": "Gift of the Homesteader" }, { "itemId": 102901, "count": 1, "name": "Gift of Klobjarne Geirr" }, { "itemId": 103973, "count": 1, "name": "Nyr Hrammr" }] },
    "105653": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "106273": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "110020": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 110020, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 110142, "count": 1, "name": "Fledgling Constellation" }, { "itemId": 110081, "count": 1, "name": "Gift of the Tenebral Ward" }, { "itemId": 110008, "count": 1, "name": "Gift of Reality" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }] },
    "87109": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 87109, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 87037, "count": 1, "name": "Claw of Resolution" }, { "itemId": 87115, "count": 1, "name": "Gift of the Four Legions" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 73239, "count": 1, "name": "Gift of Maguuma Mastery" }] },
    "95612": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 95612, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 96827, "count": 1, "name": "Dragon's Tail" }, { "itemId": 95846, "count": 1, "name": "Gift of Aurene's Tail" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "95675": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 95675, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 95994, "count": 1, "name": "Dragon's Fang" }, { "itemId": 96790, "count": 1, "name": "Gift of Aurene's Fang" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "95684": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 95684, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 95920, "count": 1, "name": "Dragon's Weight" }, { "itemId": 96161, "count": 1, "name": "Gift of Aurene's Weight" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "95808": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 95808, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 96915, "count": 1, "name": "Dragon's Argument" }, { "itemId": 96493, "count": 1, "name": "Gift of Aurene's Argument" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "96028": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 96028, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 97691, "count": 1, "name": "Dragon's Scale" }, { "itemId": 96073, "count": 1, "name": "Gift of Aurene's Scale" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "96203": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 96203, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 95967, "count": 1, "name": "Dragon's Claw" }, { "itemId": 97066, "count": 1, "name": "Gift of Aurene's Claw" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "96221": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 96221, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 96193, "count": 1, "name": "Dragon's Wisdom" }, { "itemId": 97552, "count": 1, "name": "Gift of Aurene's Wisdom" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "96356": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 96356, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 96357, "count": 1, "name": "Dragon's Bite" }, { "itemId": 97027, "count": 1, "name": "Gift of Aurene's Bite" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "96652": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 96652, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 95814, "count": 1, "name": "Dragon's Insight" }, { "itemId": 97281, "count": 1, "name": "Gift of Aurene's Insight" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "96937": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 96937, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 97449, "count": 1, "name": "Dragon's Rending" }, { "itemId": 97804, "count": 1, "name": "Gift of Aurene's Rending" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "97077": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 97077, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 96330, "count": 1, "name": "Dragon's Wing" }, { "itemId": 96015, "count": 1, "name": "Gift of Aurene's Wing" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "97099": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 97099, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 96925, "count": 1, "name": "Dragon's Breath" }, { "itemId": 95922, "count": 1, "name": "Gift of Aurene's Breath" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "97165": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 97165, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 96303, "count": 1, "name": "Dragon's Gaze" }, { "itemId": 97088, "count": 1, "name": "Gift of Aurene's Gaze" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "97377": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 97377, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 97267, "count": 1, "name": "Dragon's Persuasion" }, { "itemId": 97412, "count": 1, "name": "Gift of Aurene's Persuasion" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "97590": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 97590, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 95834, "count": 1, "name": "Dragon's Flight" }, { "itemId": 95777, "count": 1, "name": "Gift of Aurene's Flight" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "97783": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 97783, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 97513, "count": 1, "name": "Dragon's Voice" }, { "itemId": 96354, "count": 1, "name": "Gift of Aurene's Horn" }, { "itemId": 96137, "count": 1, "name": "Draconic Tribute" }, { "itemId": 96033, "count": 1, "name": "Gift of Jade Mastery" }] },
    "80111": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80111, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80460, "count": 1, "name": "Refined Envoy Gloves" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80131": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80131, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80264, "count": 1, "name": "Refined Envoy Mantle" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80145": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80145, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80366, "count": 1, "name": "Refined Envoy Shoulderpads" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80161": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80161, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80658, "count": 1, "name": "Refined Envoy Vambraces" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80190": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80190, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80120, "count": 1, "name": "Refined Envoy Vestments" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80205": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80205, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80673, "count": 1, "name": "Refined Envoy Gauntlets" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80248": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80248, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80441, "count": 1, "name": "Refined Envoy Cowl" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80252": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80252, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80675, "count": 1, "name": "Refined Envoy Leggings" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80254": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80254, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80648, "count": 1, "name": "Refined Envoy Breastplate" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80277": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80277, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80427, "count": 1, "name": "Refined Envoy Tassets" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80281": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80281, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80177, "count": 1, "name": "Refined Envoy Boots" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80296": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80296, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80634, "count": 1, "name": "Refined Envoy Mask" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80356": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80356, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80275, "count": 1, "name": "Refined Envoy Pants" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80384": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80384, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80387, "count": 1, "name": "Refined Envoy Helmet" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80399": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80399, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80583, "count": 1, "name": "Refined Envoy Shoes" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80435": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80435, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80236, "count": 1, "name": "Refined Envoy Pauldrons" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80557": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80557, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80127, "count": 1, "name": "Refined Envoy Greaves" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "80578": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 80578, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 80607, "count": 1, "name": "Refined Envoy Jerkin" }, { "itemId": 78866, "count": 1, "name": "Gift of Prosperity" }, { "itemId": 78989, "count": 1, "name": "Gift of Prowess" }, { "itemId": 78936, "count": 1, "name": "Gift of Dedication" }] },
    "82093": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82093, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81420, "count": 1, "name": "Triumphant Hero's Shinplates" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82098": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82102": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82109": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82173": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82173, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81285, "count": 1, "name": "Triumphant Hero's Epaulets" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82180": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82196": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82196, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81418, "count": 1, "name": "Triumphant Hero's Legplates" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82214": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82214, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67128, "count": 1, "name": "Ardent Glorious Shinplates" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "82245": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82245, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67117, "count": 1, "name": "Ardent Glorious Wristplates" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "82268": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82272": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82334": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82348": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82401": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82410": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82423": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82437": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82437, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81315, "count": 1, "name": "Triumphant Hero's Faceguard" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82456": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82456, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81349, "count": 1, "name": "Triumphant Hero's Gauntlets" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82465": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82465, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67144, "count": 1, "name": "Ardent Glorious Gauntlets" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "82502": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82512": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82512, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67157, "count": 1, "name": "Ardent Glorious Legguards" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "82519": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82519, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67148, "count": 1, "name": "Ardent Glorious Footgear" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "82552": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82670": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82670, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67115, "count": 1, "name": "Ardent Glorious Brigandine" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "82698": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82801": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82801, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81336, "count": 1, "name": "Triumphant Hero's Wargreaves" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82902": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82902, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81476, "count": 1, "name": "Triumphant Hero's Masque" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82903": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82903, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81386, "count": 1, "name": "Triumphant Hero's Legguards" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82925": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "82963": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82963, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81333, "count": 1, "name": "Triumphant Hero's Pauldrons" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "82994": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 82994, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81446, "count": 1, "name": "Triumphant Hero's Shoulderguards" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "83036": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83036, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81338, "count": 1, "name": "Triumphant Hero's Raiment" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "83087": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83094": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83113": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83113, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67118, "count": 1, "name": "Ardent Glorious Raiment" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83127": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83127, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67147, "count": 1, "name": "Ardent Glorious Pauldrons" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83162": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83162, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67131, "count": 1, "name": "Ardent Glorious Armguards" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83240": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83289": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83289, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81500, "count": 1, "name": "Triumphant Hero's Footgear" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "83308": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83323": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83323, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67146, "count": 1, "name": "Ardent Glorious Legplates" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83348": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83348, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67143, "count": 1, "name": "Ardent Glorious Breastplate" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83394": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83394, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81304, "count": 1, "name": "Triumphant Hero's Breastplate" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "83482": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83497": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83497, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81279, "count": 1, "name": "Triumphant Hero's Leggings" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "83595": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83595, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67152, "count": 1, "name": "Ardent Glorious Epaulets" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83676": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83699": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83702": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83729": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83862": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "83921": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83921, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67145, "count": 1, "name": "Ardent Glorious Plate Helm" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83929": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 83929, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67158, "count": 1, "name": "Ardent Glorious Shoulderguards" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "83957": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84110": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84110, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81489, "count": 1, "name": "Triumphant Hero's Wristplates" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "84176": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84176, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81330, "count": 1, "name": "Triumphant Hero's Warhelm" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "84181": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84301": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84341": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84427": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84461": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84481": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84508": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84546": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84546, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67151, "count": 1, "name": "Ardent Glorious Leggings" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "84561": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84578": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84578, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81434, "count": 1, "name": "Triumphant Hero's Brigandine" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "84629": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84629, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81428, "count": 1, "name": "Triumphant Hero's Armguards" }, { "itemId": 82746, "count": 1, "name": "Gift of War Prosperity" }, { "itemId": 84168, "count": 1, "name": "Gift of War Prowess" }, { "itemId": 83259, "count": 1, "name": "Gift of War Dedication" }] },
    "84633": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84633, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67141, "count": 1, "name": "Ardent Glorious Crown" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "84643": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84643, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67156, "count": 1, "name": "Ardent Glorious Cap" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "84655": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 84655, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 67142, "count": 1, "name": "Ardent Glorious Wargreaves" }, { "itemId": 84174, "count": 1, "name": "Gift of Competitive Prosperity" }, { "itemId": 82350, "count": 1, "name": "Gift of Competitive Prowess" }, { "itemId": 84203, "count": 1, "name": "Gift of Competitive Dedication" }] },
    "84723": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "84748": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89093": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89094": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89101": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89117": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89126": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89134": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89152": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89158": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89167": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89174": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89183": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89209": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89234": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89235": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89245": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89252": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89260": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "89266": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "101460": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101460, "outputCount": 1, "disciplines": ["Armorsmith"], "ingredients": [{ "itemId": 100946, "count": 1, "name": "Arcanum of Astral Footprints" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101462": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101462, "outputCount": 1, "disciplines": ["Tailor"], "ingredients": [{ "itemId": 100524, "count": 1, "name": "Arcanum of Astral Bearing" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101499": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101499, "outputCount": 1, "disciplines": ["Tailor"], "ingredients": [{ "itemId": 100509, "count": 1, "name": "Arcanum of Astral Heartbeat" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101501": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101501, "outputCount": 1, "disciplines": ["Tailor"], "ingredients": [{ "itemId": 100198, "count": 1, "name": "Arcanum of Astral Stride" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101516": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101516, "outputCount": 1, "disciplines": ["Tailor"], "ingredients": [{ "itemId": 100706, "count": 1, "name": "Arcanum of Astral Thought" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101521": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101521, "outputCount": 1, "disciplines": ["Armorsmith"], "ingredients": [{ "itemId": 100509, "count": 1, "name": "Arcanum of Astral Heartbeat" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101535": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101535, "outputCount": 1, "disciplines": ["Tailor"], "ingredients": [{ "itemId": 100946, "count": 1, "name": "Arcanum of Astral Footprints" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101536": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101536, "outputCount": 1, "disciplines": ["Tailor"], "ingredients": [{ "itemId": 100050, "count": 1, "name": "Arcanum of Astral Grasp" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101544": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101544, "outputCount": 1, "disciplines": ["Armorsmith"], "ingredients": [{ "itemId": 100706, "count": 1, "name": "Arcanum of Astral Thought" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101551": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101551, "outputCount": 1, "disciplines": ["Armorsmith"], "ingredients": [{ "itemId": 100524, "count": 1, "name": "Arcanum of Astral Bearing" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101556": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101556, "outputCount": 1, "disciplines": ["Leatherworker"], "ingredients": [{ "itemId": 100509, "count": 1, "name": "Arcanum of Astral Heartbeat" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101568": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101568, "outputCount": 1, "disciplines": ["Armorsmith"], "ingredients": [{ "itemId": 100198, "count": 1, "name": "Arcanum of Astral Stride" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101570": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101570, "outputCount": 1, "disciplines": ["Leatherworker"], "ingredients": [{ "itemId": 100050, "count": 1, "name": "Arcanum of Astral Grasp" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101579": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101579, "outputCount": 1, "disciplines": ["Leatherworker"], "ingredients": [{ "itemId": 100198, "count": 1, "name": "Arcanum of Astral Stride" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101602": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101602, "outputCount": 1, "disciplines": ["Leatherworker"], "ingredients": [{ "itemId": 100946, "count": 1, "name": "Arcanum of Astral Footprints" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101609": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101609, "outputCount": 1, "disciplines": ["Armorsmith"], "ingredients": [{ "itemId": 100050, "count": 1, "name": "Arcanum of Astral Grasp" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100933, "count": 1, "name": "Gift of Mighty Prosperity" }] },
    "101614": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101614, "outputCount": 1, "disciplines": ["Leatherworker"], "ingredients": [{ "itemId": 100706, "count": 1, "name": "Arcanum of Astral Thought" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "101645": { "craftType": "crafting", "dataStatus": "recipe", "recipeId": 101645, "outputCount": 1, "disciplines": ["Leatherworker"], "ingredients": [{ "itemId": 100524, "count": 1, "name": "Arcanum of Astral Bearing" }, { "itemId": 100852, "count": 1, "name": "Gift of Expertise" }, { "itemId": 100288, "count": 1, "name": "Gift of Stormy Skies" }, { "itemId": 100512, "count": 1, "name": "Gift of Magical Prosperity" }] },
    "105171": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "105293": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "105317": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "105921": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "106178": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "106658": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "95380": { "craftType": "none", "dataStatus": "no_recipe", "ingredients": [] },
    "81908": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 81908, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81729, "count": 1, "name": "Spark of Sentience" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 81796, "count": 1, "name": "Gift of Sentience" }, { "itemId": 81861, "count": 1, "name": "Gift of Draconic Mastery" }] },
    "91048": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 91048, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 91035, "count": 1, "name": "Glimpse" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 90985, "count": 1, "name": "Gift of Prescience" }, { "itemId": 91041, "count": 1, "name": "Gift of Arid Mastery" }] },
    "91234": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 91234, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 86104, "count": 1, "name": "Hateful Sworl" }, { "itemId": 91193, "count": 1, "name": "Gift of Patience" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 91225, "count": 1, "name": "Gift of Compassion" }] },
    "92991": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 92991, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 93036, "count": 1, "name": "Gift of the Champion" }, { "itemId": 79980, "count": 1, "name": "Mist Pendant" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 77485, "count": 1, "name": "Gift of Skirmishing" }] },
    "93105": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 93105, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 93190, "count": 1, "name": "Gift of the World" }, { "itemId": 80058, "count": 1, "name": "Mist Band (Infused)" }, { "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 81371, "count": 1, "name": "Gift of Conquering" }] },
    "95093": { "craftType": "none", "dataStatus": "placeholder", "ingredients": [] },
    "107022": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 107022, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 107040, "count": 1, "name": "Gift of Rays" }, { "itemId": 106712, "count": 1, "name": "Gift of the Survivors" }, { "itemId": 105804, "count": 1, "name": "Gift of the People" }, { "itemId": 106986, "count": 1, "name": "Gift of the Hylek" }] },
    "109012": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 109012, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 109686, "count": 1, "name": "Gift of the Mist Warrior" }, { "itemId": 109618, "count": 1, "name": "Gift of the Mistwalker" }, { "itemId": 109363, "count": 1, "name": "Gift of the Warclaw" }] },
    "109070": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 109070, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 71820, "count": 1, "name": "Mystic Tribute" }, { "itemId": 109469, "count": 1, "name": "Gift of Galdra" }, { "itemId": 109161, "count": 1, "name": "Gift of Shadowstones" }, { "itemId": 109391, "count": 1, "name": "Vial of Liquid Shadowstone" }] },
    "77474": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 77474, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 77509, "count": 1, "name": "Gift of the Competitor" }, { "itemId": 77485, "count": 1, "name": "Gift of Skirmishing" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 77536, "count": 1, "name": "Wings of Ascension" }] },
    "81462": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 81462, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 81467, "count": 1, "name": "Warcry" }, { "itemId": 81478, "count": 1, "name": "Gift of Warfare" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 81371, "count": 1, "name": "Gift of Conquering" }] },
    "104857": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 104857, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 104962, "count": 1, "name": "Gift of the Mistburned Isles" }, { "itemId": 104846, "count": 1, "name": "Gift of Shadows" }, { "itemId": 104872, "count": 1, "name": "Gift of the Feast" }, { "itemId": 104690, "count": 1, "name": "Orrax Contained" }] },
    "74155": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 74155, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 72309, "count": 1, "name": "Unbound" }, { "itemId": 74377, "count": 1, "name": "Gift of Infinity" }, { "itemId": 19626, "count": 1, "name": "Gift of Fortune" }, { "itemId": 37070, "count": 1, "name": "Gift of Ascension" }] },
    "91505": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 91505, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 91449, "count": 1, "name": "Gift of Sigils" }, { "itemId": 77451, "count": 1, "name": "Gift of Craftsmanship" }, { "itemId": 70867, "count": 1, "name": "Gift of Condensed Might" }, { "itemId": 76530, "count": 1, "name": "Gift of Condensed Magic" }] },
    "91536": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 91536, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 89218, "count": 1, "name": "Gift of Runes" }, { "itemId": 77451, "count": 1, "name": "Gift of Craftsmanship" }, { "itemId": 70867, "count": 1, "name": "Gift of Condensed Might" }, { "itemId": 76530, "count": 1, "name": "Gift of Condensed Magic" }] },
    "101582": { "craftType": "mystic_forge", "dataStatus": "recipe", "recipeId": 101582, "outputCount": 1, "disciplines": [], "ingredients": [{ "itemId": 101519, "count": 1, "name": "Gift of Relics" }, { "itemId": 77451, "count": 1, "name": "Gift of Craftsmanship" }, { "itemId": 76530, "count": 1, "name": "Gift of Condensed Magic" }, { "itemId": 70867, "count": 1, "name": "Gift of Condensed Might" }] },
  };

  // Devuelve la entrada de un id del catalogo, o null si el id no es del
  // catalogo. NO devuelve una entrada para 'no tengo datos': los 206 ids
  // estan TODOS en BY_ITEM, asi que una ausencia es un id desconocido y no
  // un hueco de datos. Un consumidor que distinga esos dos casos tiene que
  // mirar `dataStatus`, no la presencia de la clave.
  function get(itemId) {
    var e = BY_ITEM[Number(itemId)];
    return e === undefined ? null : e;
  }

  // Lo que la cola necesita para pintar 'de que se hace', sin que cada
  // consumidor vuelva a decidir que frase corresponde a que estado.
  function describe(itemId) {
    var e = get(itemId);
    if (!e) return null;
    if (e.dataStatus === 'placeholder') return PLACEHOLDER_NOTE;
    if (e.dataStatus === 'no_recipe') return NO_RECIPE_NOTE;
    if (e.craftType === 'crafting') {
      var d = e.disciplines && e.disciplines.length
        ? e.disciplines.join(', ')
        : 'disciplina';
      return 'Se craftea con ' + d + '.';
    }
    return 'Se hace en la Forja Mystica.';
  }

  root.LegendaryRecipes = {
    version: '1.0.0',
    generated: "2026-10-02 03:38:10 UTC",
    totalItems: 206,
    craftType: CRAFT_TYPE,
    dataStatus: DATA_STATUS,
    placeholder: PLACEHOLDER,
    noRecipeNote: NO_RECIPE_NOTE,
    counts: {
      craftType: { mystic_forge: 124, crafting: 18, none: 64 },
      dataStatus: { recipe: 142, no_recipe: 63, placeholder: 1 }
    },
    byItem: BY_ITEM,
    get: get,
    describe: describe
  };

  console.info('[LegendaryRecipes]', 'Contrato cargado: 206 items, ' +
    'mystic_forge=124 crafting=18 none=64');
})(typeof window !== 'undefined' ? window : this);
